version: '3.8'

services:
  postgres:
    container_name: stock-control-container
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stock-control
      PGDATA: /docker/pg
    volumes:
      - ./data/pg:/docker/pg
